name: Test

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@3
        width:
          distribution: zulu
          java-version: 17

      - name: Test
        run: ./gradlew test
